apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: m20lilos0-go 
  janus-idp.io/tekton: m20lilos0-go
  backstage.io/kubernetes-id: m20lilos0-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: m20lilos0-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml